---

- hosts: 192.168.33.10

  tasks:
  - name : Update APT
    become: true
    apt:
      update_cache: yes

  - name: Install OpenJDK Java
    become: yes
    apt:
      name: openjdk-8-jdk
      state: present

  - name: Install Maven
    become: yes
    apt:
      name: maven
      state: latest

  - name: Install Git
    become: yes
    apt:
      name: git
      state: present
