--- 
- name: installer tomcat 9 sur une machine ubuntu 16.04
  become: yes
  hosts: 192.168.33.40
  tasks:
    - name: installer JAVA 
      apt:
        update_cache: yes
        name: default-jre
    - name:  créer un groupe tomcat
      group:
        name: tomcat
        system: yes    
    - name: créer un utilisateur tomcat 
      user:
        name: tomcat
        group: tomcat
        state: present
        home: /opt/tomcat
        shell: /bin/false      
        system: yes
    - name: télecharger tomcat
      get_url:
        url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.43/bin/apache-tomcat-9.0.43.tar.gz 
        dest: /opt/tomcat/apache-tomcat-9.0.43.tar.gz
    - name: unarchiver le fichier tar dans le répertoire /opt/tomcat
      unarchive:
        remote_src: yes
        src: /opt/tomcat/apache-tomcat-9.0.43.tar.gz
        dest: /opt/tomcat/
    - name: supprimer l'arviche .tar.gz
      file:
        path: /opt/tomcat/apache-tomcat-9.0.43.tar.gz
        state: absent
    - name: ajout d'un lien symbolique
      file:
        src: /opt/tomcat/apache-tomcat-9.0.43
        path: /opt/tomcat/latest
        state: link
    - name: changement owner du repertoire opt/tomcat/
      file:
        path: /opt/tomcat
        recurse: yes
        owner: tomcat       
        group: tomcat 
    - name: creer un systemd service pour tomcat
      template:
        src: tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service
        owner: root
        group: root
        mode: 0755
    - name: relaod systemd daemon
      systemd:
        daemon_reload: yes
    - name: start tomcat service
      service:
        name: tomcat
        state: started
        enabled: yes
